> This is a self-correcting activity generated by [nbgrader](https://nbgrader.readthedocs.io). Fill in any place that says `YOUR CODE HERE` or `YOUR ANSWER HERE`. Run subsequent cells to check your code.

---

# Preprocessing functions

## Environment setup

In [2]:
import numpy as np
%autosave 0

Autosave disabled


## Training/test set splitting

### Question

Complete the following function to split `data` between training and test sets, according to the `test_size` ratio.

In [9]:
def train_test_split(data, test_size):
    limit = int(len(data)*(1-test_size))
    return data[:limit], data[limit:]

In [10]:
# Generate a random (30,3) tensor
x = np.random.rand(30, 3)

x_train, x_test = train_test_split(x, .25)
print(f'x_train: {x_train.shape}. x_test: {x_test.shape}')

assert x_train.shape == (22,3)
assert x_test.shape == (8,3)

x_train: (22, 3). x_test: (8, 3)


In [11]:
# Generate a random (30,3) tensor
x = np.random.rand(30, 3)

x_train, x_test = train_test_split(x, .33)
print(f'x_train: {x_train.shape}. x_test: {x_test.shape}')

assert x_train.shape == (20,3)
assert x_test.shape == (10,3)

x_train: (20, 3). x_test: (10, 3)


## Feature scaling

### Question

Complete the following function to implement min-max feature scaling.

In [14]:
def scale_min_max(data):
    return (data - np.min(data)) / (np.max(data) - np.min (data))

In [15]:
# Generate a random (3,3) tensor with values between 1 and 10
x = np.random.randint(1, 10, (3,3))

x_scaled = scale_min_max(x)
print(x_scaled)

assert x_scaled.min() == 0
assert x_scaled.max() == 1

[[0.6 0.  0.6]
 [0.6 0.  0. ]
 [1.  0.4 0.2]]


### Question

Complete the following function to implement feature scaling by standardization.

In [16]:
def scale_standard(data, mean=None, std=None):
    return (data -np.mean(data)) / np.std(data)

In [17]:
# Generate a random (3,3) tensor with values between 1 and 10
x = np.random.randint(1, 10, (3,3))

x_scaled = scale_standard(x)
print(x_scaled)

mean_scaled = x_scaled.mean()
std_scaled = x_scaled.std()
print(f'Mean: {mean_scaled}. Std: {std_scaled}')

assert np.abs(np.max(mean_scaled)) < 10**-6
assert np.abs(np.max(std_scaled - 1)) < 10**-6

[[-0.18844459 -1.20604538 -0.52764485]
 [ 1.16835646 -1.20604538  1.16835646]
 [ 0.15075567  1.50755672 -0.86684512]]
Mean: 1.1102230246251565e-16. Std: 1.0


### Question

Use the previous function to scale `x_train` and `x_test` while preventing information leakage from the test set.

In [18]:
x_train = scale_standard(x_train, mean=np.mean(x_train), std=np.std(x_train))
x_test = scale_standard(x_test, mean=np.mean(x_test), std=np.std(x_test))

## Feature encoding

### Question

Complete the following function to one-hot encode a class vector (integers) into a matrix of binary vectors.

In [49]:
def one_hot_encode(elements):
    result = np.zeros((len(elements), max(elements) + 1))
    for i, element in enumerate(elements):
        result[i, element] = 1
    
    return result

In [50]:
x = np.array([0, 5, 3])

x_hot = one_hot_encode(x)
print(x_hot)

assert np.array_equal(x_hot[0], [1, 0, 0, 0, 0, 0])
assert np.array_equal(x_hot[1], [0, 0, 0, 0, 0, 1])
assert np.array_equal(x_hot[2], [0, 0, 0, 1, 0, 0])

[[1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0.]]


In [51]:
x = np.array([3, 2, 1, 4, 2, 3])

x_hot = one_hot_encode(x)
print(x_hot)

assert np.array_equal(x_hot[0], [0, 0, 0, 1, 0])
assert np.array_equal(x_hot[1], [0, 0, 1, 0, 0])
assert np.array_equal(x_hot[2], [0, 1, 0, 0, 0])
assert np.array_equal(x_hot[3], [0, 0, 0, 0, 1])
assert np.array_equal(x_hot[4], [0, 0, 1, 0, 0])
assert np.array_equal(x_hot[5], [0, 0, 0, 1, 0])

[[0. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]]
